=== OPTiBAR/OPTiBAR/src/core/parser/schemas/input.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "input",
    "title": "Parse Input",
    "description": "This data is passed to the autocad drawing service to generate the .dwg output.",
    "type": "object",
    "properties": {
        "version": {
            "description": "version of the used scheme",
            "type": "integer"
        },
        "strips": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "stations": {
                        "type": "array",
                        "items": {
                            "type": "number"
                        }
                    },
                    "design": {
                        "type": "object",
                        "properties": {
                            "shear": {
                                "description": "needed steel density for shear",
                                "type": "array",
                                "items": {
                                    "type": "number",
                                    "minimum": 0
                                }    
                            },
                            "flexural": {
                                "description": "the steel area needed for flexure.",
                                "type": "object",
                                "properties": {
                                    "top": {
                                        "type": "array",
                                        "items": {
                                            "type": "number",
                                            "minimum": 0
                                        }
                                    },
                                    "bottom": {
                                        "type": "array",
                                        "items": {
                                            "type": "number",
                                            "minimum": 0
                                        }
                                    }
                                },
                                "required": [ "top", "bottom" ]        
                            },
                            "moment": {
                                "description": "the moment if each station",
                                "type": "object",
                                "properties": {
                                    "top": {
                                        "type": "array",
                                        "items": {
                                            "type": "number"
                                        }
                                    },
                                    "bottom": {
                                        "type": "array",
                                        "items": {
                                            "type": "number"
                                        }
                                    }
                                },
                                "required": [ "top", "bottom" ]
                            }
                        },
                        "required": [ "shear", "flexural", "moment"]
                    },
                    "geometry": {
                        "type": "object",
                        "properties": {
                            "widths": {
                                "type": "array",
                                "items": {
                                    "type": "number",
                                    "minimum": 0
                                }
                            },
                            "line_points": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "point": {
                                            "type": "array",
                                            "items": [
                                                {
                                                    "description": "x coordinate of the point.",
                                                    "type": "number"
                                                },
                                                {
                                                    "description": "y coordinate of the point.",
                                                    "type": "number"
                                                }
                                            ],
                                            "additionalItems": false
                                        },
                                        "margin": {
                                            "type": "array",
                                            "items": [
                                                {
                                                    "description": "left margin",
                                                    "type": "number",
                                                    "minimum": 0
                                                },
                                                {
                                                    "description": "right margin",
                                                    "type": "number",
                                                    "minimum": 0
                                                }
                                            ],
                                            "additionalItems": false
                                        }
                                    },
                                    "required": [ "point", "margin" ] 
                                },
                                "minItems": 2    
                            },
                            "covers": {
                                "type": "object",
                                "properties": {
                                    "top": {
                                        "type": "number",
                                        "minimum": 0
                                    },
                                    "bottom": {
                                        "type": "number",
                                        "minimum": 0
                                    }
                                }
                            }
                        },
                        "required": [ "line_points", "widths" , "covers"]
                    },
                    "fy": {
                        "type": "number",
                        "exclusiveMinimum": 0
                    }
                },
                "required": [ "stations", "design", "geometry", "fy" ]
            }
        },
        "areas": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "is_opening": {
                        "type": "boolean"
                    },
                    "prop": {
                        "description": "if area is not an opening this property is required",
                        "type": "object",
                        "properties": {
                            "thickness": {
                                "type": "number",
                                "exclusiveMinimum": 0
                            },
                            "fc": {
                                "type": "number",
                                "exclusiveMinimum": 0
                            }
                        },
                        "required": ["thickness", "fc"]
                    },
                    "corners": {
                        "type": "array",
                        "items": {
                            "description": "each item is a point",
                            "type": "array",
                            "items":[
                                {
                                    "description": "the x coordinate of the point",
                                    "type": "number"
                                },
                                {
                                    "description": "the y coordinate of the point",
                                    "type": "number"
                                }
                            ]
                        }
                    }
                },
                "required": [ "name", "is_opening", "corners" ]
            }
        },
        "columns": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "point": {
                        "description": "the center point of the column",
                        "type": "array",
                        "items": [
                            {
                                "description": "x coordanate of the point",
                                "type": "number"
                            },
                            {
                                "description": "y coordinate of the point",
                                "type": "number"
                            }
                        ]
                    },
                    "dim": {
                        "description": "dimension of the column",
                        "type": "array",
                        "items": [
                            {
                                "description": "the xdim of the column",
                                "type": "number",
                                "exclusiveMinimum": 0
                            },
                            {
                                "description": "the ydim of the column",
                                "type": "number",
                                "exclusiveMinimum": 0
                            }
                        ]
                    }
                },
                "required": [ "point", "dim" ]
            }
        },
        "grid": {
            "type": "object",
            "properties": {
                "X": {
                    "description": "the x value of the grid lines with constant x value.",
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "ordinate": {
                                "type": "number"
                            }
                        },
                        "required": [ "name", "ordinate" ]
                    }
                },
                "Y": {
                    "description": "the y value of the grid lines with constant y value.",
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "ordinate": {
                                "type": "number"
                            }
                        },
                        "required": [ "name", "ordinate" ]
                    }
                }
            },
            "required": [ "X", "Y" ]
        }
    },
    "required": [ "version", "grid", "columns", "areas", "strips" ]
}

=== OPTiBAR/OPTiBAR/src/core/tests/data_files/parsed_data.json
{
    "version": 1,
    "strips": [
        {
            "name": "CSA1",
            "stations": [
                0.0,
                1.07808,
                2.15616,
                3.23424,
                4.31232,
                5.3904,
                6.0,
                6.6096,
                7.80822857142857,
                9.00685714285714,
                10.2054857142857,
                11.4041142857143,
                12.6027428571429,
                13.8013714285714,
                15.0,
                16.0,
                17.0,
                18.0
            ],
            "design": {
                "shear": [
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.01034213638305664,
                    0.01034213638305664,
                    0.00210152220726014,
                    0.01439881324768066,
                    0.00956293106079102,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0
                ],
                "flexural": {
                    "top": [
                        0.000681523376464844,
                        0.000594499572753906,
                        0.000253319396972656,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.000697115356445313,
                        0.00499586083984375,
                        0.010132900390625,
                        0.0098323671875,
                        0.006808095703125,
                        0.00289058422851562,
                        0.00293350268554688,
                        0.00131365441894531,
                        0.000904675415039062
                    ],
                    "bottom": [
                        0.000745227294921875,
                        0.00165761315917969,
                        0.00516809521484375,
                        0.0129817568359375,
                        0.02505047265625,
                        0.0452209765625,
                        0.0085234462890625,
                        0.04870170703125,
                        0.02556714453125,
                        0.010158603515625,
                        0.00219584008789063,
                        0.000189810180664062,
                        0.000205335083007812,
                        0.000620811584472656,
                        0.0,
                        0.000243459762573242,
                        0.000288971221923828,
                        0.000277076354980469
                    ]
                },
                "moment": {
                    "top": [
                        -19.3170695542501,
                        -16.852953927798,
                        -7.18528004627179,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        -19.7551477881584,
                        -140.313718139473,
                        -281.178977109904,
                        -272.609941375014,
                        -189.895654285163,
                        -80.6504467786293,
                        -82.5351107182834,
                        -37.1242477899954,
                        -25.5931208813862
                    ],
                    "bottom": [
                        21.1204123512339,
                        46.9056754995153,
                        145.371601819467,
                        360.291907234722,
                        680.735929203211,
                        1185.09072960166,
                        1834.13953122563,
                        1265.20814380611,
                        691.586466525759,
                        282.605888003551,
                        62.0300766947319,
                        5.38394812961907,
                        5.82393282492034,
                        17.5891596507563,
                        0.269509358058478,
                        6.90369969581626,
                        8.19264054133629,
                        7.85513406026156
                    ]
                }
            },
            "geometry": {
                "widths": [
                    6.0,
                    6.0,
                    6.0,
                    6.0,
                    6.0,
                    6.0,
                    6.0,
                    5.84760009765625,
                    5.54794287109375,
                    5.24828564453125,
                    4.94862841796875,
                    4.64897119140625,
                    4.349314453125,
                    4.0496572265625,
                    1.75,
                    3.5,
                    3.25,
                    3.0
                ],
                "line_points": [
                    {
                        "point": [
                            0.0,
                            15.0
                        ],
                        "margin": [
                            3.0,
                            3.0
                        ]
                    },
                    {
                        "point": [
                            6.0,
                            15.0
                        ],
                        "margin": [
                            3.0,
                            3.0
                        ]
                    },
                    {
                        "point": [
                            18.0,
                            15.0
                        ],
                        "margin": [
                            0.0,
                            3.0
                        ]
                    }
                ],
                "covers": {
                    "top": 0.1,
                    "bottom": 0.1
                }
            },
            "fy": 40788.6476888968
        },
        {
            "name": "CSB1",
            "stations": [
                0.0,
                1.0,
                2.0,
                3.0,
                4.0,
                5.0,
                6.0,
                7.0,
                8.0,
                9.0,
                10.0,
                11.0,
                12.0,
                12.3,
                13.3,
                14.3,
                15.0,
                15.755
            ],
            "design": {
                "shear": [
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.01034213638305664,
                    0.01034213638305664,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0
                ],
                "flexural": {
                    "top": [
                        0.000367043975830078,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.000600229675292969,
                        0.00354285498046875,
                        0.00747954638671875,
                        0.0064485751953125,
                        0.0057243857421875,
                        0.00679724560546875,
                        0.006011271484375,
                        0.00315600561523437
                    ],
                    "bottom": [
                        0.000377915008544922,
                        0.001649951171875,
                        0.0054291279296875,
                        0.012385029296875,
                        0.0217372890625,
                        0.03638434765625,
                        0.0096411787109375,
                        0.03605859765625,
                        0.022161896484375,
                        0.0133642705078125,
                        0.006862791015625,
                        0.00355578295898437,
                        0.00237973217773437,
                        0.00151177893066406,
                        0.0,
                        0.000483890228271484,
                        0.00110851147460937,
                        0.000779550170898437
                    ]
                },
                "moment": {
                    "top": [
                        -14.6937840207436,
                        -4.97275124608367,
                        0.0,
                        0.0,
                        0.0,
                        -19.5318674676176,
                        0.0,
                        -14.1785108237652,
                        0.0,
                        0.0,
                        -24.022134694827,
                        -141.290348467369,
                        -296.874083274308,
                        -185.254624058365,
                        -163.862825255506,
                        -195.157494255968,
                        -172.817910856859,
                        -90.6863923866361
                    ],
                    "bottom": [
                        15.1287835275243,
                        65.9505248821815,
                        216.024170219205,
                        488.664445295732,
                        847.912371987494,
                        1393.68102846662,
                        2080.51497144444,
                        1381.76693205022,
                        864.023587620162,
